openapi: 3.0.4

info:
  title: Tennis Game API
  version: 1.0.0
  description: API for simulating a tennis game by processing points

servers:
  - url: http://localhost:8070
    description: Optional server description, e.g. Main (production) server

tags:
  - name: tennis-game

paths:
  /tennis/play:
    post:
      tags:
        - tennis-game
      summary: Play a tennis game set
      description: return score
      operationId: playSet
      requestBody:
        description: A sequence of points wins by Player A or B("AAABB")
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InputGame"
      responses:
        "200":
          description: Game score
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScoreResponse"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    InputGame:
      type: string
      example: "AAABB"
    ScoreResponse:
      type: array
      items:
        type: string
        example: "Player A : 15 / Player B : 0"
    ErrorId:
      description: >
        Error identifier. Defined errors include:
          - TECHNICAL_ERROR: a technical error occurred (HTTP code 500)
      type: string
      enum:
        - TECHNICAL_ERROR
    ApplicationError:
      description: Generic format for returned error
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ErrorId"
        message:
          description: Error message
          type: string
    TennisGameException:
      required:
        - code
        - message
        - status
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        code:
          type: string
  responses:
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TennisGameException"
          example: |
            {
              "status": 500,
              "message": "An unexpected error occurred",
              "code": "INTERNAL_SERVER_ERROR"
            }